server:
  port: 8068
  servlet:
    context-path: /base/api

#数据源配置
spring:
  datasource:
    #serverTimezone是定义时区,mysql高版本需要定义这些东西,useSSL也是高版本mysql需要问有没有用SSL连接
    url: jdbc:mysql://127.0.0.1:3306/base?serverTimezone=GMT%2B8&useSSL=FALSE&allowPublicKeyRetrieval=true
    username: root
    password: 19971214
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    # Redis服务器地址
    host: localhost
    #Redis服务器连接端口
    port: 6379
    #password:
    # Redis数据库索引（默认为0）
    database: 1
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000

# mybatis-plus相关配置
mybatis-plus:
  #配置别名
  type-aliases-package: com.ws.base.model
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"自增",NONE:"未设置主键",INPUT:"手动输入",ASSIGN_ID:"默认全局唯一ID",ASSIGN_UUID:"全局唯一的UUID";
      id-type: ASSIGN_UUID
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
    #启动打印LOGO开关
    banner: false
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#jwt: data :这个路径是根据JWTUtil中的
#@ConfigurationProperties("jwt.data")配置的
jwt:
  data:
    #    jwt加密密钥
    SECRET: jwt-token-secret
    #      jwt的过期时间(24h)
    expiration: 86400000